### ISSUE TITLE
[GitHub Checks] Add a lint step to verify a valid URL

### ISSUE THREAD

**Issue by KyleJu** [web-platform-tests/wpt-metadata#591]
In GitHub checks, there should be a step to verify if a URL is valid. There have been cases where the URLs have extra quotation marks, e.g. `'crbug.com/1053965'` or invalid `crbug.com/foo`. This lint should probably live under [parse_test.go](https://github.com/web-platform-tests/wpt-metadata/blob/master/parse_test.go)

**Comment by KyleJu** [comment]
https://github.com/web-platform-tests/wpt-metadata/pull/588

**Comment by stephenmcgruer** [comment]
This is fine and well, but then the wpt.fyi backend (or frontend, either) should probably make sure the links its sending here will pass the lint. Otherwise we'll just get a bunch of stuck PRs?

**Comment by KyleJu** [comment]
> This is fine and well, but then the wpt.fyi backend (or frontend, either) should probably make sure the links its sending here will pass the lint. Otherwise we'll just get a bunch of stuck PRs?

Good point. I think having a check on the frontend is a better option since users don't have to triage again, if anything goes wrong. Will file a separate issue on wpt fyi as well

**Comment by foolip** [comment]
I went to fix more of these issues in https://github.com/web-platform-tests/wpt-metadata/pull/777 so that I don't have to normalize the URLs in a script I'm trying out. That revealed that the lack of normalization of URLs has also led to some duplicate entries, and in some cases I suspect someone has done duplicate work to link the bug twice after a first attempt didn't work.

Ensuring that URLs are valid URLs and further normalizing them for each bug tracker we know about would help here. That means normalizing "https://crbug.com/1234" to "https://bugs.chromium.org/p/chromium/issues/detail?id=1234" or vice versa.

**Comment by foolip** [comment]
@KyleJu are you still planning to work on this? I discovered using the script in https://github.com/web-platform-tests/wpt-metadata/pull/1762 that we had a non-URL which I'm removing in https://github.com/web-platform-tests/wpt-metadata/pull/1769.

**Comment by foolip** [comment]
Another: https://github.com/web-platform-tests/wpt-metadata/pull/1770

**Comment by foolip** [comment]
And with 3 more I've fixed all the invalid URLs I think: https://github.com/web-platform-tests/wpt-metadata/pull/1771 + https://github.com/web-platform-tests/wpt-metadata/pull/1772 + https://github.com/web-platform-tests/wpt-metadata/pull/1773
